name: Scala CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    
    - name: Set up JDK 1.8
      uses: actions/setup-java@v1
      with:
        java-version: 1.8
    
    - name: Login to DockerHub Registry
      run: echo ${{ secrets.DOCKERHUB_PASSWORD }} | docker login -u ${{ secrets.DOCKERHUB_USERNAME }} --password-stdin

    - name: Get the version
      id: vars
      run: echo ::set-output name=tag::$(echo ${GITHUB_REF:10})
    
    - name: Check SBT version
      run: sbt sbtVersion
      
    - name: Run tests
      run: sbt test
      
    - name: Docker build
      run: docker build -t scala-play .

    - name: Build the tagged Docker image
      run: docker build . --file Dockerfile --tag oliveirafernando/scala-play:${{steps.vars.outputs.tag}}
    
    - name: Docker images
      run: docker images
