name: Scala CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up JDK 1.8
      uses: actions/setup-java@v1
      with:
        java-version: 1.8
    - name: Check SBT version
      run: sbt sbtVersion
    - name: Run tests
      run: sbt test
    - name: Docker build
      run: docker build -t scala-play .
    - name: Docker images
      run: docker images