name: Scala CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    
    - name: Set up JDK 1.8
      uses: actions/setup-java@v1
      with:
        java-version: 1.8
    
    - name: Login to DockerHub Registry
      run: echo ${{ secrets.DOCKERHUB_PASSWORD }} | docker login -u ${{ secrets.DOCKERHUB_USERNAME }} --password-stdin
    
    - name: Check SBT version
      run: sbt sbtVersion
      
    - name: Run tests
      run: sbt test

    - name: Build the tagged Docker image
      run: docker build --file Dockerfile --tag oliveirafernando/scala-play:latest .

    - name: Docker images
      run: docker images

    - name: Push the latest Docker image
      run: docker push oliveirafernando/scala-play:latest

  test-to-run-when-pr-merged-to-master:
    needs: build
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/master'
    steps:
      - run: echo "Event name = ${{github.event_name}} , Event action = ${{github.event.action}} , Event PR Merged = ${{github.event.pull_request.merged}} , Github REFS ${{github.ref}}"
